### ISSUE TITLE
🍊 Jupyter Notebook

### ISSUE THREAD

**Issue by camenduru** [Tencent/HunyuanVideo#10]
Thanks for the project ❤️ I made a jupyter notebook 🥳 I hope you like it.

https://github.com/camenduru/hunyuan-video-jupyter

**Comment by zhoudaquan** [comment]
> Thanks for the project ❤️ I made a jupyter notebook 🥳 I hope you like it.
> 
> https://github.com/camenduru/hunyuan-video-jupyter

Thanks for your interest in our work and we do appreciate your efforts in setting up the jupyter notebook. As the released model weights is an accelerated version, we recommend you to increase the diffusion steps to 50 for better performance.

Best regards,
DQ

**Comment by camenduru** [comment]
@zhoudaquan Gradio demo: https://github.com/camenduru/hunyuan-video-tost/blob/main/worker_runpod_gradio.py

**Comment by FurkanGozukara** [comment]
@camenduru awesome work but i see 0 optimization atm 🗡️ 

is that possible to have some quant or like cpu offloading or more optimizations @zhoudaquan

**Comment by camenduru** [comment]
@FurkanGozukara https://github.com/kijai/ComfyUI-HunyuanVideoWrapper

**Comment by FurkanGozukara** [comment]
@camenduru thanks i really trying to avoid comfyui :D
