### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by misakaikato** [Tencent/HunyuanVideo#11]
ZH：
我使用了 python sample_video.py --video-size 544 960 --video-length 129 --infer-steps 30 --prompt "a cat is running, realistic." --flow-reverse --seed 0 --use-cpu-offload --save-path ./results 运行，当开始进行第一步的时候，出现了Floating point exception (core dumped)

![image](https://github.com/user-attachments/assets/35469dab-506a-4a36-ae43-e41c6b949ab7)

使用其他分辨率也是一样的错误

EN：
I ran the command python sample_video.py --video-size 544 960 --video-length 129 --infer-steps 30 --prompt 'a cat is running, realistic.' --flow-reverse --seed 0 --use-cpu-offload --save-path ./results, and when it started the first step, I encountered a 'Floating point exception (core dumped)' error.

**Comment by chenxx89** [comment]
> > Hi, Thanks for your interest in our work. We have not met this error before. Can you list your running environment and GPU type?
> 
> Thank you for your reply. The environment I am using is as follows:
> 
> NVIDIA H20 CUDA 12.7 Python 3.10.15 Memory: 150G
> 
> As for other software versions, they are as specified in the project requirements.

try to install torch based on CUDA 11.8 version

**Comment by chenxx89** [comment]
> > Hi, Thanks for your interest in our work. We have not met this error before. Can you list your running environment and GPU type?
> 
> Thank you for your reply. The environment I am using is as follows:
> 
> NVIDIA H20 CUDA 12.7 Python 3.10.15 Memory: 150G
> 
> As for other software versions, they are as specified in the project requirements.

you can try installing torch based on CUDA 11.8 version

**Comment by pineleen** [comment]
I meet the seem issue with docker image:hunyuanvideo:cuda_12  on H20. 
Floating point exception (core dumped) when inference self.mlp(t_freq) in TimestepEmbedder.

**Comment by misakaikato** [comment]
> > > Hi, Thanks for your interest in our work. We have not met this error before. Can you list your running environment and GPU type? We haven't encountered this error before. Can you list your operating environment and GPU type?
> > 
> > 
> > Thank you for your reply. The environment I am using is as follows: Thank you for your reply. The environment I use is as follows:
> > NVIDIA H20 CUDA 12.7 Python 3.10.15 Memory: 150GNVIDIA H20 CUDA 12.7 Python 3.10.15 Memory: 150G
> > As for other software versions, they are as specified in the project requirements.
> 
> you can try installing torch based on CUDA 11.8 version

It worked, thanks

**Comment by pineleen** [comment]
> I meet the seem issue with docker image:hunyuanvideo:cuda_12 on H20. Floating point exception (core dumped) when inference self.mlp(t_freq) in TimestepEmbedder.

cuda_11 is ok.

**Comment by OutstanderWang** [comment]
The float point exception on H20 is a known hardware and cublas problem. Nvidia suggests that all H20 users update the cublas version to solve it.  The suggested cublas version is 12.4.5.8.

**Comment by zhoudaquan** [comment]
I found this issue has no follow-up questions. Please re-open it if needed.
