### ISSUE TITLE
Embeded classifier free guidance?

### ISSUE THREAD

**Issue by kinam0252** [Tencent/HunyuanVideo#113]
Thank you for your amazing work! 😊

In this model, it seems to use **embedded CFG** rather than the usual approach of predicting noise first and then applying CFG. 
Could you provide **insights into how exactly this works?** Or are there any **previous works** that might be helpful?

**Comment by jiawangbai** [comment]
Thanks for your interest in our work. It is more efficient to use embedded CFG compared to two separated branches during inference (approximately 1.9x acceleration). For more details, please refer to Section 5.2 of our technical report  (https://arxiv.org/pdf/2412.03603).

**Comment by kinam0252** [comment]
Thank you so much!
