### ISSUE TITLE
Can not find file 'sample_video_parallel.py'

### ISSUE THREAD

**Issue by PP7364** [Tencent/HunyuanVideo#135]
I have used the following command for video generation
but I can not find the file 'sample_video_parallel.py'
where it is?

'''
cd HunyuanVideo

torchrun --nproc_per_node=4 sample_video_parallel.py \
    --video-size 1280 720 \
    --video-length 129 \
    --infer-steps 50 \
    --prompt "A cat walks on the grass, realistic style." \
    --flow-reverse \
    --seed 42 \
    --ulysses_degree 4 \
    --ring_degree 1 \
    --save-path ./results
'''
![123](https://github.com/user-attachments/assets/018201ff-2550-4b82-93c9-f2480c571ea9)

**Comment by xibosun** [comment]
We merged it into sample_video.py. Please refer to the instructions from the latest commit https://github.com/Tencent/HunyuanVideo/tree/main?tab=readme-ov-file#using-command-line-1

**Comment by PP7364** [comment]
Thanks for your answer, but i still can not get it , can you help write a command for example? 
THANK YOU!!!
