### ISSUE TITLE
Plan for opening source the prompt transformation model?

### ISSUE THREAD

**Issue by Bob-cheng** [Tencent/HunyuanVideo#149]
Hi,

I am wondering whether you have the plan to open source the prompt transformation model you claimed in your paper? It is the LLM model that you used to transform users' text prompts to the video generation input for the text-to-video model. The video generation model seems cannot follow my prompts well in its current form and I hope the additional transformation model could help.

Thanks,
Bob

**Comment by jpgallegoar** [comment]
https://huggingface.co/tencent/HunyuanVideo-PromptRewrite

**Comment by Bob-cheng** [comment]
Thanks for your reply. However, it is too large for me to deploy... Is it finetuned on Hunyuan-Large?
