### ISSUE TITLE
 how long it takes to inference a 720px1280px129f video?

### ISSUE THREAD

**Issue by xiangweifeng** [Tencent/HunyuanVideo#2]

**Comment by zhoudaquan** [comment]
Hi, the released model has acceleration tricks. It also supports multiple resolutions. The largest resolution supported is 720x1280, which takes ~17min with 30 diffusion steps on the H800 GPU model.

**Comment by feifeibear** [comment]
You might want to consider exploring xDiT for parallel inference to potentially reduce latency.

https://github.com/xdit-project/xDiT

**Comment by XWalways** [comment]
A100-SXM4-80GB 50 steps takes ~47min

**Comment by mikeyimer** [comment]
> A100-SXM4-80GB 50 steps takes ~47min

May I ask, approximately how much vram is being used?

**Comment by XWalways** [comment]
***@***.***

**Comment by zhanghanduo** [comment]
> > A100-SXM4-80GB 50 steps takes ~47min
> 
> May I ask, approximately how much vram is being used?

74GB/80GB with cpu-offload off

**Comment by nxoor** [comment]
A800：height: 720
                         width: 1280
                  video_length: 129
                        prompt: ['A cat walks on the grass, realistic style.']
                    neg_prompt: ['Aerial view, aerial view, overexposed, low quality, deformation, a poor composition, bad hands, bad teeth, bad eyes, bad limbs, distortion']
                          seed: None
                   infer_steps: 50
         num_videos_per_prompt: 1
                guidance_scale: 1.0
                      n_tokens: 118800
                    flow_shift: 7.0
       embedded_guidance_scale: 6.0
       50分钟

**Comment by Ondrej-Dusek** [comment]
> @xiangweifeng #68 We have successfully implemented xDiT to significantly accelerate model inference. We would greatly appreciate it if you could keep an eye on our PR and provide any feedback or suggestions you might have.

hi @feifeibear - exciting! May I ask - how much does this accelerate the inference?

**Comment by feifeibear** [comment]
> > @xiangweifeng #68 We have successfully implemented xDiT to significantly accelerate model inference. We would greatly appreciate it if you could keep an eye on our PR and provide any feedback or suggestions you might have.
> 
> hi @feifeibear - exciting! May I ask - how much does this accelerate the inference?

We have presented the latency on the readme of our PR. 8xH100 is 5 minutes.
