### ISSUE TITLE
Get Only Noise result

### ISSUE THREAD

**Issue by PrivateMaRyan** [Tencent/HunyuanVideo#31]
I downloaded all the weights and did inference following the Readme, but got only noise result.
![image](https://github.com/user-attachments/assets/781876a0-1b65-4ee9-a66e-8ddd35194372)

I wonder whether the released model support other resolutions that also satisfied 9:16 ratio like (288 x 512, 576 x 1024) for a rapid evaluation

**Comment by TianQi-777** [comment]
Thanks for your interest in our work. Can you provide the resolution you tested?

**Comment by PrivateMaRyan** [comment]
> Thanks for your interest in our work. Can you provide the resolution you tested for this noise result?

你们是腾讯我就不说英文了，太累。我贴图这张是288x512x65f的，是为了验证输出。但我也用过原始的720x1280x129f出结果，也是这种。

当然，我不确定问题是不是来自hyvideo/modules/attention.py当中，我装不上flash_attn这个包，我把attention函数的关键词mode=“torch"进行的推理。这个地方会有影响吗

**Comment by PrivateMaRyan** [comment]
> screenshot



> I tested the flash version of 288x512x65f, and the output is acceptable.
> 
> The torch version is still under development, and the output is abnormal. We will fix this problem in the future. We currently recommend using flash mode.
> 
> However, the pure noise result does not seem to be caused by mode=“torch", it seems like the weights are not loaded correctly. Can you share a screenshot of the weights being loaded.

![image](https://github.com/user-attachments/assets/cc6ca7a0-ef3e-4b55-a6c2-730a980c0e14)
this is the log of my last test(the output was still noise) even after my successfully install flash_atten package。And I downloaded all the weigths again

**Comment by TianQi-777** [comment]
We can align the model parameters. You can add the following code in `HunyuanVideo/hyvideo/inference.py`
```
class HunyuanVideoSampler(Inference):
    def __init__(
        self,
        args,
        vae,
        vae_kwargs,
        text_encoder,
        model,
        text_encoder_2=None,
        pipeline=None,
        use_cpu_offload=False,
        device=0,
        logger=None,
    ):
        super().__init__(
            args,
            vae,
            vae_kwargs,
            text_encoder,
            model,
            text_encoder_2=text_encoder_2,
            pipeline=pipeline,
            use_cpu_offload=use_cpu_offload,
            device=device,
            logger=logger,
        )

        # ====================================================================================
        # add code
        # ====================================================================================
        count_vae_sum = 0
        count_text_encoder_mean = 0
        count_text_encoder_2_sum = 0
        count_model_sum = 0

        for k, v in self.vae.named_parameters():
            count_vae_sum += v.sum()
        for k, v in self.text_encoder.named_parameters():
            count_text_encoder_mean += v.mean()
        for k, v in self.text_encoder_2.named_parameters():
            count_text_encoder_2_sum += v.sum()
        for k, v in self.model.named_parameters():
            count_model_sum += v.sum()
        print(f"vae params sum: {count_vae_sum}")
        print(f"text_encoder params mean: {count_text_encoder_mean}")
        print(f"text_encoder_2 params sum: {count_text_encoder_2_sum}")
        print(f"model params sum: {count_model_sum}")
        # ==================================================================================

```

vae params sum: -7036.0
text_encoder params mean: 28.25
text_encoder_2 params sum: 25312.0
model params sum: -4161536.0

**Comment by PrivateMaRyan** [comment]
> We can align the model parameters. You can add the following code in `HunyuanVideo/hyvideo/inference.py`
> 
> ```
> class HunyuanVideoSampler(Inference):
>     def __init__(
>         self,
>         args,
>         vae,
>         vae_kwargs,
>         text_encoder,
>         model,
>         text_encoder_2=None,
>         pipeline=None,
>         use_cpu_offload=False,
>         device=0,
>         logger=None,
>     ):
>         super().__init__(
>             args,
>             vae,
>             vae_kwargs,
>             text_encoder,
>             model,
>             text_encoder_2=text_encoder_2,
>             pipeline=pipeline,
>             use_cpu_offload=use_cpu_offload,
>             device=device,
>             logger=logger,
>         )
> 
>         # ====================================================================================
>         # add code
>         # ====================================================================================
>         count_vae_sum = 0
>         count_text_encoder_mean = 0
>         count_text_encoder_2_sum = 0
>         count_model_sum = 0
> 
>         for k, v in self.vae.named_parameters():
>             count_vae_sum += v.sum()
>         for k, v in self.text_encoder.named_parameters():
>             count_text_encoder_mean += v.mean()
>         for k, v in self.text_encoder_2.named_parameters():
>             count_text_encoder_2_sum += v.sum()
>         for k, v in self.model.named_parameters():
>             count_model_sum += v.sum()
>         print(f"vae params sum: {count_vae_sum}")
>         print(f"text_encoder params mean: {count_text_encoder_mean}")
>         print(f"text_encoder_2 params sum: {count_text_encoder_2_sum}")
>         print(f"model params sum: {count_model_sum}")
>         # ==================================================================================
> ```
> 
> vae params sum: -7036.0 text_encoder params mean: 28.25 text_encoder_2 params sum: 25312.0 model params sum: -4161536.0

https://github.com/user-attachments/assets/ddb0978c-c3a3-4e54-9d01-ba7c7d4aee63
got the acceptable result! THANK YOU !
