### ISSUE TITLE
How to run on multiple GPUs?

### ISSUE THREAD

**Issue by legendier** [Tencent/HunyuanVideo#33]
I have 4 pieces of 4090 24GB, but it seems that the model only loads one GPU. How can I perform multi GPU inference?

**Comment by JacobKong** [comment]
We are working on it by using xdit, stay tuned.

**Comment by Howe2018** [comment]
mark

**Comment by wangzhihui-zh** [comment]
1

**Comment by air55555** [comment]
+100500

**Comment by ryonWang** [comment]
同问，我两个GPU，24GB*2，执行时只加载了一个GPU，所以报错了

**Comment by badarrrr** [comment]
+1！

**Comment by corticalstack** [comment]
+1

**Comment by feifeibear** [comment]
#68 Hello all, please refer to the merge request from [xDiT](https://github.com/xdit-project/xDiT) Team.

**Comment by Backroads4Me** [comment]
Has anyone been able to get xDiT to work?   It appears to still try to allocate all VRAM to the first GPU.

**Comment by feifeibear** [comment]
> Has anyone been able to get xDiT to work? It appears to still try to allocate all VRAM to the first GPU.

Leveraging xDiT can not reduce VRAM memory requirements since it applies sequence parallel. The parameters are duplicated on multiple GPUs.

**Comment by badarrrr** [comment]
sample_video_parallel.py文件在哪里呀

**Comment by feifeibear** [comment]
> sample_video_parallel.py文件在哪里呀

按照readme指令follow

cd HunyuanVideo

torchrun --nproc_per_node=8 sample_video.py \
    --video-size 1280 720 \
    --video-length 129 \
    --infer-steps 50 \
    --prompt "A cat walks on the grass, realistic style." \
    --flow-reverse \
    --seed 42 \
    --ulysses-degree 8 \
    --ring-degree 1 \
    --save-path ./results

**Comment by badarrrr** [comment]
感谢回复，我试一下！（readme写的是sample_video_parallel我以为有新的文件

**Comment by sunshinewhy** [comment]
> 感谢回复，我试一下！（不好意思只看了中文readme写的是sample_video_parallel） ![image](https://private-user-images.githubusercontent.com/141792862/393728915-9149ceea-9f59-4a1e-9424-5c13e70552f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzkwMjIsIm5iZiI6MTczNDA3ODcyMiwicGF0aCI6Ii8xNDE3OTI4NjIvMzkzNzI4OTE1LTkxNDljZWVhLTlmNTktNGExZS05NDI0LTVjMTNlNzA1NTJmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QwODMyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTQ1ZDAxNThhNTgwYjE4NTFlMzMzMTExYzJlZjkwNjIxMjEwMzcwOGM0YzQzZmJlMjVlZTNkMTkzMmVmNDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ibECo7q0u_q9u4J0J_XTuFJmkD5pNsR7AddfBlDvHdQ)

Can you tell me where is the sample_video_parallel.py python file, I can't find it. Thanks!

**Comment by badarrrr** [comment]
use sample_video.py,It works.
sample_video_parallel.py 看起来是笔误

> > 感谢回复，我试一下！（不好意思只看了中文readme写的是sample_video_parallel） ![image](https://private-user-images.githubusercontent.com/141792862/393728915-9149ceea-9f59-4a1e-9424-5c13e70552f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzkwMjIsIm5iZiI6MTczNDA3ODcyMiwicGF0aCI6Ii8xNDE3OTI4NjIvMzkzNzI4OTE1LTkxNDljZWVhLTlmNTktNGExZS05NDI0LTVjMTNlNzA1NTJmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QwODMyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTQ1ZDAxNThhNTgwYjE4NTFlMzMzMTExYzJlZjkwNjIxMjEwMzcwOGM0YzQzZmJlMjVlZTNkMTkzMmVmNDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ibECo7q0u_q9u4J0J_XTuFJmkD5pNsR7AddfBlDvHdQ)
> 
> Can you tell me where is the sample_video_parallel.py python file, I can't find it. Thanks!

**Comment by Backroads4Me** [comment]
@zhoudaquan  I see you are closing all of the multi-GPU tickets.   Has something been changed?
