### ISSUE TITLE
提示词过长时，文件无法保存

### ISSUE THREAD

**Issue by shuangyiskr** [Tencent/HunyuanVideo#37]
![QQ20241204-160246](https://github.com/user-attachments/assets/9b4d9501-9d51-4cdd-915e-2ad4636505af)

**Comment by PrivateMaRyan** [comment]
> ![QQ20241204-160246](https://private-user-images.githubusercontent.com/128061113/392279720-9b4d9501-9d51-4cdd-915e-2ad4636505af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTk3OTUsIm5iZiI6MTczMzI5OTQ5NSwicGF0aCI6Ii8xMjgwNjExMTMvMzkyMjc5NzIwLTliNGQ5NTAxLTlkNTEtNGNkZC05MTVlLTJhZDQ2MzY1MDVhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwODA0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzlkYjE5NWY3Njc5ZTE2YzJmZWJmZDg4NmY5NGVmNjdiNTk0ODY1ZmY3YjA3MjkwYWMxOGMwM2U5MTQ3NjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QvSVvTMJq0fpS__f0GJz_0T5KoT-IXjjuw-3NosSfOs)

那你就吧代码里的save_path那一句改成 save_path = "./results/00001.mp4"不就完了

**Comment by shuangyiskr** [comment]
> > ![QQ20241204-160246](https://private-user-images.githubusercontent.com/128061113/392279720-9b4d9501-9d51-4cdd-915e-2ad4636505af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTk3OTUsIm5iZiI6MTczMzI5OTQ5NSwicGF0aCI6Ii8xMjgwNjExMTMvMzkyMjc5NzIwLTliNGQ5NTAxLTlkNTEtNGNkZC05MTVlLTJhZDQ2MzY1MDVhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwODA0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzlkYjE5NWY3Njc5ZTE2YzJmZWJmZDg4NmY5NGVmNjdiNTk0ODY1ZmY3YjA3MjkwYWMxOGMwM2U5MTQ3NjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QvSVvTMJq0fpS__f0GJz_0T5KoT-IXjjuw-3NosSfOs)
> 
> 那你就吧代码里的save_path那一句改成 save_path = "./results/00001.mp4"不就完了

感谢，我的解决思路：在/HunyuanVideo/hyvideo/file_util.py中修改save_videos_grid函数，添加了一段代码
# Truncate filename if it's too long to avoid OSError
    max_filename_length = 128  # Maximum allowed length on most Unix systems
    
    if len(path) > max_filename_length:
        # Keep extension and use hash or timestamp for uniqueness
        path = f"{path[:127]}.mp4"
![image](https://github.com/user-attachments/assets/15b6f2e8-6f67-4718-b879-0dcc916db156)

**Comment by JacobKong** [comment]
可以在文件名上边做个截断，我们会 fix 一下这个问题～
