### ISSUE TITLE
CUDA unknown error

### ISSUE THREAD

**Issue by Bl1tzcrank** [Tencent/HunyuanVideo#38]
![b817327d478df5b4e1ef2b950fdb72e](https://github.com/user-attachments/assets/e60a984c-85d8-4ce3-a0f6-a8eae10031a3)
I face this bug when i download the textencoder.I run this code:python hyvideo/utils/preprocess_text_encoder_tokenizer_utils.py --input_dir ckpts/llava-llama-3-8b-v1_1-transformers --output_dir ckpts/text_encoder
Should I download both textencoder to run this model? Or just need one? I hope someone can tell me and help me to solve this bug
My cuda version is 12.1. Thanks a lot :)

**Comment by JacobKong** [comment]
what's your pytorch version?

**Comment by Bl1tzcrank** [comment]
> what's your pytorch version?

2.1.1+cu121,by the way, I try to run a video with this model by use sample_video.py and face the same bug. Is there any problem on my environment?

**Comment by Bl1tzcrank** [comment]
> #47 You can try the docker image built by myself.

Okay, I will try. Thk :)

**Comment by Bl1tzcrank** [comment]
> #47 You can try the docker image built by myself.

Okay, I will try. Thk :)
