### ISSUE TITLE
ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModel

### ISSUE THREAD

**Issue by bendanzzc** [Tencent/HunyuanVideo#41]
when i use official code to load text_encoder ,it has this error. How can I solve it? Thanks

**Comment by xiakj** [comment]
> when i use official code to load text_encoder ,it has this error. How can I solve it? Thanks

![image](https://github.com/user-attachments/assets/8a368f1c-0ad5-429c-baf6-45cd39da4c00)

**Comment by GFENGG** [comment]
Hello, i meet the same error with you,  how can i solve it? thanks very much!

ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModel

**Comment by bendanzzc** [comment]
I follow readme step by step and it works, you can follow this for instruction:
https://github.com/Tencent/HunyuanVideo/blob/main/ckpts/README.md
