### ISSUE TITLE
运行失败：python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1

### ISSUE THREAD

**Issue by 397688551** [Tencent/HunyuanVideo#51]
<img width="931" alt="image" src="https://github.com/user-attachments/assets/cc97cf9d-35fe-4862-a149-9c8f93914995">

详细：
python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1
Collecting git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1
  Cloning https://github.com/Dao-AILab/flash-attention.git (to revision v2.5.9.post1) to /tmp/pip-req-build-0193ysvf
  Running command git clone --filter=blob:none --quiet https://github.com/Dao-AILab/flash-attention.git /tmp/pip-req-build-0193ysvf
  Running command git checkout -q e2e4333c955b829d0e6087d27ee435f55c80d3a5

  Resolved https://github.com/Dao-AILab/flash-attention.git to commit e2e4333c955b829d0e6087d27ee435f55c80d3a5
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... -
done
Requirement already satisfied: torch in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from flash_attn==2.5.9.post1) (2.1.1)
Requirement already satisfied: einops in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from flash_attn==2.5.9.post1) (0.7.0)
Requirement already satisfied: filelock in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from torch->flash_attn==2.5.9.post1) (3.13.1)
Requirement already satisfied: typing-extensions in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from torch->flash_attn==2.5.9.post1) (4.11.0)
Requirement already satisfied: sympy in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from torch->flash_attn==2.5.9.post1) (1.13.2)
Requirement already satisfied: networkx in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from torch->flash_attn==2.5.9.post1) (3.3)
Requirement already satisfied: jinja2 in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from torch->flash_attn==2.5.9.post1) (3.1.4)
Requirement already satisfied: fsspec in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from torch->flash_attn==2.5.9.post1) (2024.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from jinja2->torch->flash_attn==2.5.9.post1) (2.1.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages (from sympy->torch->flash_attn==2.5.9.post1) (1.3.0)
Building wheels for collected packages: flash_attn
  Building wheel for flash_attn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]

      torch.__version__  = 2.1.1

      /aistudio/workspace/system-default/envs/hunyuan/lib/python3.10/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      Guessing wheel URL:  https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.9.post1/flash_attn-2.5.9.post1+cu122torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
      error: Remote end closed connection without response
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash_attn
  Running setup.py clean for flash_attn
Failed to build flash_attn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (flash_attn)

**Comment by TianQi-777** [comment]
We have updated the readme, you can try the following command
```
python -m pip install ninja
python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1
```

**Comment by MikeAiJF** [comment]
> 我们已经更新了 readme，你可以尝试以下命令
> 
> ```
> python -m pip install ninja
> python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1
> ```

你好，请问下面两个我应该下那个，谢谢，因为我的git有些问题无法使用
flash attn-2.5.9.post1+cu118torch2.1cxx11abiFALSE-cp39-cp39-linux x86 64.whl
flash attn-2.5.9,post1+cu118torch2.1cxx11abiTRUE-cp310-cp310-linux x86 64.whl

**Comment by TianQi-777** [comment]
This depends on the Python version of your environment. If the environment is Python 3.9, use `flash attn-2.5.9.post1+cu118torch2.1cxx11abiFALSE-cp39-cp39-linux x86 64.whl`.  If the environment is Python 3.10 use `flash attn-2.5.9,post1+cu118torch2.1cxx11abiTRUE-cp310-cp310-linux x86 64.whl`.

**Comment by MikeAiJF** [comment]
![image](https://github.com/user-attachments/assets/43655c3a-c48a-40b6-9940-de96f8500b25)
这是我的环境，能麻烦你看看吗，真心感谢

**Comment by TianQi-777** [comment]
You can try this command
```
FLASH_ATTENTION_FORCE_BUILD=TRUE pip install flash attn-2.5.9,post1+cu118torch2.1cxx11abiTRUE-cp310-cp310-linux x86 64.whl
```

**Comment by TianQi-777** [comment]
> ![image](https://private-user-images.githubusercontent.com/146935101/392762429-43655c3a-c48a-40b6-9940-de96f8500b25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTk1MjcsIm5iZiI6MTczMzM5OTIyNywicGF0aCI6Ii8xNDY5MzUxMDEvMzkyNzYyNDI5LTQzNjU1YzNhLWM0OGEtNDBiNi05OTQwLWRlOTZmODUwMGIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQxMTQ3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzc2M2E3MDFmZGJlMjFlM2ZiNmJmYzJhMjE0YjNkMmIxZGMxM2FhYTJlNGU4MjJhNjU0NDE3ZTA2Y2Q2ZTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PQjUzIFqnsrpvdP0_1H4EJh_KuLVlUAC_t9XCz0r6JM) 这是我的环境，能麻烦你看看吗，真心感谢

You can try this command
```
pip uninstall flash-attn


FLASH_ATTENTION_FORCE_BUILD=TRUE pip install flash attn-2.5.9,post1+cu118torch2.1cxx11abiTRUE-cp310-cp310-linux x86 64.whl
```
Make sure these 3 files exist after execution
```
/home/kmks-server-02/miniconda3/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn-2.5.9.post1.dist-info/*
/home/kmks-server-02/miniconda3/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn/*
/home/kmks-server-02/miniconda3/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so
```

**Comment by QiZhao-NJU** [comment]
Same issue occurs when install flash-attention:

Collecting git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1
  Cloning https://github.com/Dao-AILab/flash-attention.git (to revision v2.5.9.post1) to /tmp/pip-req-build-kbvf_b0j
  Running command git clone --filter=blob:none --quiet https://github.com/Dao-AILab/flash-attention.git /tmp/pip-req-build-kbvf_b0j
  Running command git checkout -q e2e4333c955b829d0e6087d27ee435f55c80d3a5
  Resolved https://github.com/Dao-AILab/flash-attention.git to commit e2e4333c955b829d0e6087d27ee435f55c80d3a5
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-kbvf_b0j/setup.py", line 115, in <module>
          raise RuntimeError(
      RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.


      torch.__version__  = 2.1.1


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by TianQi-777** [comment]
> Same issue occurs when install flash-attention:
> 
> Collecting git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1 Cloning https://github.com/Dao-AILab/flash-attention.git (to revision v2.5.9.post1) to /tmp/pip-req-build-kbvf_b0j Running command git clone --filter=blob:none --quiet https://github.com/Dao-AILab/flash-attention.git /tmp/pip-req-build-kbvf_b0j Running command git checkout -q e2e4333c955b829d0e6087d27ee435f55c80d3a5 Resolved https://github.com/Dao-AILab/flash-attention.git to commit e2e4333c955b829d0e6087d27ee435f55c80d3a5 Running command git submodule update --init --recursive -q Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [11 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/tmp/pip-req-build-kbvf_b0j/setup.py", line 115, in raise RuntimeError( RuntimeError: FlashAttention is only supported on CUDA 11.6 and above. Note: make sure nvcc has a supported version by running nvcc -V.
> 
> ```
>   torch.__version__  = 2.1.1
> 
> 
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

---
According to `RuntimeError: FlashAttention is only supported on CUDA 11.6 and above. Note: make sure nvcc has a supported version by running nvcc -V.`
It seems that your CUDA version (CUDA 11.6) is too old. We recommend that you upgrade to at least CUDA 11.8.

**Comment by MikeAiJF** [comment]
> pip uninstall flash-attn
/project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn-2.5.9.post1.dist-info/*
    /project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn/*
    /project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so
    有这三个文件但是在project_05下有影响吗，我是按照命令装的

**Comment by TianQi-777** [comment]
> > pip uninstall flash-attn
> > /project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn-2.5.9.post1.dist-info/*
> > /project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn/*
> > /project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so
> > 有这三个文件但是在project_05下有影响吗，我是按照命令装的

You must make sure that your flash-attn is installed in the Python environment you are executing.
```
# If you run the code using python, use the following command to confirm the Python environment you executed. 
which python

# If you run the code using python3, use the following command to confirm the Python environment you executed. 
which python3
```

The Python environment (`/home/kmks-server-02/miniconda3/envs/HunyuanVideo/lib/python3.10`) you are running is inconsistent with the Python environment (`/project_05/envs/HunyuanVideo/lib/python3.10`) where you installed flash-attn.

**Comment by MikeAiJF** [comment]
> > > pip uninstall flash-attn 
> > > /project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn-2.5.9.post1.dist-info/* 
> > > /project_05/envs/HunyuanVideo/lib/python3.10/site-包/flash_attn/* 
> > > /project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so
> > > 但是这三个文件在project_05下有影响吗，我是按照命令安装的
> 
> 你必须确保你的 flash-attn 安装在你正在执行的 Python 环境中。
> 
> ```
> # If you run the code using python, use the following command to confirm the Python environment you executed. 
> which python
> 
> # If you run the code using python3, use the following command to confirm the Python environment you executed. 
> which python3
> ```
> 
> 您正在运行的Python 环境 ( ) 与安装 flash-attn 的`/home/kmks-server-02/miniconda3/envs/HunyuanVideo/lib/python3.10`Python 环境 ( ) 不一致。`/project_05/envs/HunyuanVideo/lib/python3.10`
我按照这个命令装的FLASH_ATTENTION_FORCE_BUILD=TRUE pip install flash_attn-2.5.9.post1+cu118torch2.1cxx11abiTRUE-cp310-cp310-linux_x86_64.whl
但是不知道为什么还是在project_05下面
![image](https://github.com/user-attachments/assets/b4323f2b-4ff0-414d-b093-62e76c7ce4a1)

**Comment by TianQi-777** [comment]
> > > > pip uninstall flash-attn
> > > > /project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn-2.5.9.post1.dist-info/*
> > > > /project_05/envs/HunyuanVideo/lib/python3.10/site-包/flash_attn/*
> > > > /project_05/envs/HunyuanVideo/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so
> > > > 但是这三个文件在project_05下有影响吗，我是按照命令安装的
> > 
> > 
> > 你必须确保你的 flash-attn 安装在你正在执行的 Python 环境中。
> > ```
> > # If you run the code using python, use the following command to confirm the Python environment you executed. 
> > which python
> > 
> > # If you run the code using python3, use the following command to confirm the Python environment you executed. 
> > which python3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 您正在运行的Python 环境 ( ) 与安装 flash-attn 的`/home/kmks-server-02/miniconda3/envs/HunyuanVideo/lib/python3.10`Python 环境 ( ) 不一致。`/project_05/envs/HunyuanVideo/lib/python3.10`
> > 我按照这个命令装的FLASH_ATTENTION_FORCE_BUILD=TRUE pip install flash_attn-2.5.9.post1+cu118torch2.1cxx11abiTRUE-cp310-cp310-linux_x86_64.whl
> > 但是不知道为什么还是在project_05下面
> > ![image](https://private-user-images.githubusercontent.com/146935101/393142979-b4323f2b-4ff0-414d-b093-62e76c7ce4a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NTM1NzksIm5iZiI6MTczMzU1MzI3OSwicGF0aCI6Ii8xNDY5MzUxMDEvMzkzMTQyOTc5LWI0MzIzZjJiLTRmZjAtNDE0ZC1iMDkzLTYyZTc2YzdjZTRhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwNjM0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjgzOWM5Y2E0MTJjY2MwMjQyYzJmNDM1Y2E5NTAxZTk0NGQ5NTg4YjJlNDcyODc5YmU2YjA3OWFkMGVkYmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g2REBgLNs010vLCxb-WIodZrUwrzNzuao3QM5UKJi40)

Run the following command and get your `pip3 path`
```
# get pip3 path in your environment
which pip3
```
Replace `pip` in the original command with `pip3 path`
```
# Original
FLASH_ATTENTION_FORCE_BUILD=TRUE pip install flash_attn-2.5.9.post1+cu118torch2.1cxx11abiTRUE-cp310-cp310-linux_x86_64.whl

# Modified
FLASH_ATTENTION_FORCE_BUILD=TRUE [pip3 path] install flash_attn-2.5.9.post1+cu118torch2.1cxx11abiTRUE-cp310-cp310-linux_x86_64.whl
```

**Comment by MikeAiJF** [comment]
![image](https://github.com/user-attachments/assets/bb998ecd-7f06-48a3-911a-1a6395fbea70)
还是不行

**Comment by LostOxygen** [comment]
Okey a simple trick which worked for me to get flash attention up and running in the provided conda environment:

1. Check your python version (in the header when opening a python console)
2. Check your CUDA version (`nvidia-smi` in the upper right corner)
3. Check your CPython version by running `python -m pip install wheel && python -c 'from wheel.vendored.packaging import tags; print(f"{tags.interpreter_name()}{tags.interpreter_version()}", end="")'`

4. Now go to the [Flash Attention Releases Page](https://github.com/Dao-AILab/flash-attention/releases) and pick the release which matches all of your versions. Download it using `wget` or whatever. 
IMPORTANT: in my case the version labeled with  `abiTRUE` did not work, so be sure to pick the one with `abiFALSE` in the filename if this error also occurs on your system.

5. Install it via `python -m pip install flash_attention_whatever.whl`

In my case im using the conda environment delivered by this repository with Python 3.10.9, CPython 10 (CP10), and CUDA 12.4 which means i picked the `flash_attn-2.7.2.post1+cu12torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl` version.

**Comment by MikeAiJF** [comment]
> 好的，这是一个简单的技巧，它对我有用，可以在提供的 conda 环境中启动并运行 Flash 注意力：
> 
> 1. 检查你的 Python 版本（在打开 Python 控制台时的标题中）
> 2. 检查你的 CUDA 版本（`nvidia-smi`在右上角）
> 3. 通过运行检查你的 CPython 版本`python -m pip install wheel && python -c 'from wheel.vendored.packaging import tags; print(f"{tags.interpreter_name()}{tags.interpreter_version()}", end="")'`
> 4. 现在转到[Flash Attention Releases Page](https://github.com/Dao-AILab/flash-attention/releases)并选择与您的所有版本匹配的版本。使用`wget`或任何其他方式下载。
>    重要提示：在我的情况下，标有 的版本  `abiTRUE`不起作用，因此`abiFALSE`如果您的系统也出现此错误，请务必选择文件名中带有 的版本。
> 5. 通过安装`python -m pip install flash_attention_whatever.whl`
> 
> 就我而言，我使用此存储库提供的 conda 环境，其中包含 Python 3.10.9、CPython 10（CP10）和 CUDA 12.4，这意味着我选择了该`flash_attn-2.7.2.post1+cu12torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl`版本。

我的cuda是12.4但是我的torch-cuda-11.8版本，所以我按照作者的方法安装2.5.9版本的
