### ISSUE TITLE
加载模型的时候一直被killed

### ISSUE THREAD

**Issue by 397688551** [Tencent/HunyuanVideo#52]
<img width="985" alt="image" src="https://github.com/user-attachments/assets/83eba569-7269-442e-96c5-8c05f59c2511">

<img width="723" alt="image" src="https://github.com/user-attachments/assets/4b2d2043-94eb-46c1-963d-cf970ef98b9b">

**Comment by jinqiupeter** [comment]
你看看内存（不是GPU显存）是不是满了

**Comment by zhoudaquan** [comment]
> <img alt="image" width="985" src="https://private-user-images.githubusercontent.com/37072662/392629632-83eba569-7269-442e-96c5-8c05f59c2511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzMyNTEsIm5iZiI6MTczMzM3Mjk1MSwicGF0aCI6Ii8zNzA3MjY2Mi8zOTI2Mjk2MzItODNlYmE1NjktNzI2OS00NDJlLTk2YzUtOGMwNWY1OWMyNTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA0MjkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YWJhODY2NTE3MTNkNTA1MjNmN2ZmOGQzZjY0YjQwZDBlYzk2MDcwYTVjNzA0YzhiMWMwYjU2MGY1ZDcyNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TZJ519pA8M8Q52PqbQA9Q_dk1UkygB7VrXezzl9-Ogs"> <img alt="image" width="723" src="https://private-user-images.githubusercontent.com/37072662/392629820-4b2d2043-94eb-46c1-963d-cf970ef98b9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzMyNTEsIm5iZiI6MTczMzM3Mjk1MSwicGF0aCI6Ii8zNzA3MjY2Mi8zOTI2Mjk4MjAtNGIyZDIwNDMtOTRlYi00NmMxLTk2M2QtY2Y5NzBlZjk4YjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA0MjkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZTZmMDI4NjRjOWJiZTU5MWU2MGVlYmFlMzdkOTdjM2FkNDQ2YWJjNzg1ZmMzMmEyODEzMGQ3N2EyNjBkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.obgFpBK4-19Xlz7Lxhe8QZYhNoV9M0xu_raYJ8JLYoA">

这种情况一般是CPU使用率超了，可以考虑从这进行排查。

**Comment by 397688551** [comment]
> > <img alt="image" width="985" src="https://private-user-images.githubusercontent.com/37072662/392629632-83eba569-7269-442e-96c5-8c05f59c2511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzMyNTEsIm5iZiI6MTczMzM3Mjk1MSwicGF0aCI6Ii8zNzA3MjY2Mi8zOTI2Mjk2MzItODNlYmE1NjktNzI2OS00NDJlLTk2YzUtOGMwNWY1OWMyNTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA0MjkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YWJhODY2NTE3MTNkNTA1MjNmN2ZmOGQzZjY0YjQwZDBlYzk2MDcwYTVjNzA0YzhiMWMwYjU2MGY1ZDcyNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TZJ519pA8M8Q52PqbQA9Q_dk1UkygB7VrXezzl9-Ogs"> <img alt="image" width="723" src="https://private-user-images.githubusercontent.com/37072662/392629820-4b2d2043-94eb-46c1-963d-cf970ef98b9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzMyNTEsIm5iZiI6MTczMzM3Mjk1MSwicGF0aCI6Ii8zNzA3MjY2Mi8zOTI2Mjk4MjAtNGIyZDIwNDMtOTRlYi00NmMxLTk2M2QtY2Y5NzBlZjk4YjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA0MjkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZTZmMDI4NjRjOWJiZTU5MWU2MGVlYmFlMzdkOTdjM2FkNDQ2YWJjNzg1ZmMzMmEyODEzMGQ3N2EyNjBkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.obgFpBK4-19Xlz7Lxhe8QZYhNoV9M0xu_raYJ8JLYoA">
> 
> 这种情况一般是CPU使用率超了，可以考虑从这进行排查。

这个看不到呀，上面的图片

**Comment by badarrrr** [comment]
也是text_encoder这里

**Comment by badarrrr** [comment]
111换了内存大的服务器解决了

**Comment by 397688551** [comment]
> 111换了内存大的服务器解决了

请问多大的内存呢

**Comment by badarrrr** [comment]
现在环境是内存64 GB、gpu单卡 80 GB的可以跑

**Comment by 397688551** [comment]
> 现在环境是内存64 GB、gpu单卡 80 GB的可以跑

那确实挺大的，那我这个内存30G+显存48的是跑不起来了

**Comment by badarrrr** [comment]
刚刚看了下，我这运行的时候内存峰值拉满64G了

**Comment by 397688551** [comment]
> 刚刚看了下，我这运行的时候内存峰值拉满64G了

你那显存怎么样，也是占满了显存么

**Comment by badarrrr** [comment]
height: 720
width: 1280
video_length: 129
infer_steps: 50
gpu显存峰值72.8，利用率100%

**Comment by XZJIsme** [comment]
我用 A100，1TB 内存也一直 killed

<img width="1130" height="88" alt="Image" src="https://github.com/user-attachments/assets/09617a1b-1377-485f-9f28-10166ef22a9e" />
