### ISSUE TITLE
时间差异

### ISSUE THREAD

**Issue by sp1cae** [Tencent/HunyuanVideo#55]
您好，我在本地A800 部署使用生成50步的视频时需要将近1小时，而在app中使用该服务只需要几分钟，请问为什么会造成如此大的时间差异

**Comment by wmarkcom** [comment]
我也想知道这个问题

**Comment by WThirteen** [comment]
我使用元宝生成视频需要3分钟以上，这是因为不同设备的差异吗？

**Comment by Owen718** [comment]
+1，我也是同样的情况。
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/ae7d9d83-a344-44ab-8ff0-cc58c74e59ab">

**Comment by mondon11** [comment]
我觉得可能跟帧率设置的有关，demo的参数是129帧/秒，web上生成的是24帧/秒？我刚配完环境用A800在跑视频也是这么慢

**Comment by Changlin-Lee** [comment]
#70 请检查下是否有按照readme中的过程正确安装flash attention
`python -m pip install ninja
python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1`

**Comment by sp1cae** [comment]
> #70请检查下是否有按照readme中的过程正确安装flash注意 `python -m pip install ninja python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1`

谢谢您的解答，是在安装成功下运行的，而且flash-attention优化也不可能会有这么大的差距吧

**Comment by jiaxiangc** [comment]
> #70 请检查下是否有按照readme中的过程正确安装flash attention `python -m pip install ninja python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1`

请问flash attention会从50分钟->5分钟吗。

**Comment by zigchang** [comment]
![image](https://github.com/user-attachments/assets/4557aea0-74c8-49bf-a5ab-c98b4bf8aaaf)
Inference time on A100
