### ISSUE TITLE
Error while setting up environment

### ISSUE THREAD

**Issue by AmemiyaYuko** [Tencent/HunyuanVideo#6]
ERROR: Ignored the following versions that require a different python version: 1.1.0 Requires-Python >=3.9.0; 1.1.1 Requires-Python >=3.9.0
ERROR: Could not find a version that satisfies the requirement accelerate==1.1.1 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.24.1, 0.25.0, 0.26.0, 0.26.1, 0.27.0, 0.27.1, 0.27.2, 0.28.0, 0.29.0, 0.29.1, 0.29.2, 0.29.3, 0.30.0rc0, 0.30.0, 0.30.1, 0.31.0, 0.32.0, 0.32.1, 0.33.0, 0.34.0, 0.34.1, 0.34.2, 1.0.0rc0, 1.0.0rc1, 1.0.0, 1.0.1)
ERROR: No matching distribution found for accelerate==1.1.1

**Comment by AmemiyaYuko** [comment]
in environment.yml, python version was set to 3.8.12. Should the environment.yml file be changed?

**Comment by misakaikato** [comment]
> in environment.yml, python version was set to 3.8.12. Should the environment.yml file be changed?

I'm having the same issue... after changing the python version, it seems to be normal

**Comment by TianQi-777** [comment]
Sorry, we have updated the environment.yml file, which uses python 3.10.9.
