### ISSUE TITLE
when I use fp16 inerence， get nan result

### ISSUE THREAD

**Issue by devilztt** [Tencent/HunyuanVideo#60]
When I set precision fp16 to inerence， get Nan result,  the result is total black

GPU:V100
torch:2.4.0
python:3.10.9
![image](https://github.com/user-attachments/assets/87e76bbd-128a-4a96-b7e5-20dd31e12344)

**Comment by TianQi-777** [comment]
fp16 may have this problem, so we recommend you generate the video under the bf16 setting.

**Comment by devilztt** [comment]
> fp16 may have this problem, so we recommend you generate the video under the bf16 setting.

sure，maybe my gpu is v100， when I use bf16 inference with 3DConv it will raise cuda error

**Comment by fengyuentau** [comment]
Any chance to workaround this if using fp16 for inference?
