### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by ryonWang** [Tencent/HunyuanVideo#62]
![WX20241205-194349@2x](https://github.com/user-attachments/assets/dacc06e5-d0bc-4cb3-a15f-1a3d70558a16)
我这个报错哪位大神遇到了？我修改了max_split_size_mb也不行，加了--batch-size参数也不行，报同样错。加了cpu处理参数还是报错，我有点搞不明白是哪里出了问题

**Comment by yg33717** [comment]
看说明，最少要求45G 显存， 你这个只有24G

**Comment by JacobKong** [comment]
Thank you for your attention. You can try reducing the height, width, and video length, which will use much less memory but may result in lower quality.

**Comment by ryonWang** [comment]
> Thank you for your attention. You can try reducing the height, width, and video length, which will use much less memory but may result in lower quality.

![Uploading 截屏2024-12-09 08.59.47.png…]()
Yes, I have adjusted the configuration to a relatively lower execution level, such as video-size and video-length.

**Comment by ryonWang** [comment]
> Thank you for your attention. You can try reducing the height, width, and video length, which will use much less memory but may result in lower quality.

Yes, I have adjusted the configuration to a relatively lower execution level, such as video-size and video-length.
<img width="493" alt="截屏2024-12-09 08 59 47" src="https://github.com/user-attachments/assets/af6cd57e-fd16-4784-9109-b785fa4bb888">
