### ISSUE TITLE
Unbelievably slow

### ISSUE THREAD

**Issue by aikitoria** [Tencent/HunyuanVideo#70]
When I run the sample code and command on a H200 SXM, the currently fastest available GPU, it takes half an hour to produce the video. Is this the expected result?

**Comment by JacobKong** [comment]
Thanks for your attention. What's your environment information? We test on H800, it's took 1700s, it shall be faster on H200.

**Comment by Changlin-Lee** [comment]
> When I run the sample code and command on a H200 SXM, the currently fastest available GPU, it takes half an hour to produce the video. Is this the expected result?

Please check if the flash attention is installed properly
`python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1`

**Comment by Xushuolin** [comment]
> > When I run the sample code and command on a H200 SXM, the currently fastest available GPU, it takes half an hour to produce the video. Is this the expected result?
> 
> Please check if the flash attention is installed properly `python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1`

It  fails when I run the command `python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1`     unable to access

**Comment by Xushuolin** [comment]
Do I have to install this version @v2.5.9.post1 ?

**Comment by TianQi-777** [comment]
> Do I have to install this version @v2.5.9.post1 ?

You can try the following command
```
python -m pip install ninja
python -m pip install git+https://github.com/Dao-AILab/flash-attention.git@v2.5.9.post1
```

**Comment by aikitoria** [comment]
Yes flash-attn is installed using that exact version (that was already part of the instructions in readme.md), interestingly it only took a few seconds for it to build the wheel.

**Comment by Xushuolin** [comment]
> Yes flash-attn is installed using that exact version (that was already part of the instructions in readme.md), interestingly it only took a few seconds for it to build the wheel.

‘HEAD is now at e2e4333 Limit to MAX_JOBS=1 with CUDA 12.2’
If my cuda version is 12.3, it might not work?

**Comment by aikitoria** [comment]
The server I was using has CUDA 12.6. Surely it is not a problem to use the latest version?

**Comment by Xushuolin** [comment]
> The server I was using has CUDA 12.6. Surely it is not a problem to use the latest version?

thank you!  Supporting FlashAttention-3 would be even better
