### ISSUE TITLE
请问需要多大的显存和生成时长

### ISSUE THREAD

**Issue by MTD-xiaoma** [Tencent/HunyuanVideo#71]
4090 24G显存。跑了4个小时，一直卡在这个页面，请问是正常现象么。

<img width="1418" alt="image" src="https://github.com/user-attachments/assets/93a0df9a-4116-4e81-9356-3e4ad8662209">

**Comment by darknli** [comment]
不太正常，我a100跑是30min左右。不过24g显存竟然能跑的动？我这直接拉到60G。。

**Comment by MTD-xiaoma** [comment]
那我的应该是显存不够。
24G显存 能跑起来，应该用到了共享GPU内存，内存多了40多G，但是一直出不来。

**Comment by WangRongsheng** [comment]
A800, 60GB, 单个视频生成50分钟左右，很离谱

**Comment by zhangvia** [comment]
> 不太正常，我a100跑是30min左右。不过24g显存竟然能跑的动？我这直接拉到60G。。

你是什么输入？我看他们官方的replicate demo页面有提到h100生成，多数在八分钟内就能出结果。h100也不至于是a100的4倍速吧

**Comment by zigchang** [comment]
> 不太正常，我a100跑是30min左右。不过24g显存竟然能跑的动？我这直接拉到60G。。

你这个step设30还是50呢，默认的50我这边A100需要50分钟。

**Comment by jiaxiangc** [comment]
管线的数据类型或者设备加载是不是有问题，有能调整的空间吗

**Comment by sp1cae** [comment]
> A800, 60GB, 单个视频生成50分钟左右，很离谱

同A800 数据一致

**Comment by jiahui-w** [comment]
> A800, 60GB, 单个视频生成50分钟左右，很离谱

A100，80g，生成时间差不多

**Comment by badarrrr** [comment]
+1,，A100 80G，要跑50分钟

**Comment by tian-2024** [comment]
> 4090 24G显存。跑了4个小时，一直卡在这个页面，请问是正常现象么。
> 
> <img alt="image" width="1418" src="https://private-user-images.githubusercontent.com/68857897/393073113-93a0df9a-4116-4e81-9356-3e4ad8662209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODM0NTksIm5iZiI6MTczMzQ4MzE1OSwicGF0aCI6Ii82ODg1Nzg5Ny8zOTMwNzMxMTMtOTNhMGRmOWEtNDExNi00ZTgxLTkzNTYtM2U0YWQ4NjYyMjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDExMDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NjBhMTE3ZDFiNTI3YWMwNTRhNDNjMWQzMDVlYjUzZjJmMTZlMzE2MTQwMGM1NDljMzA1NDUwYTkyOTNhZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wbI99nYZdOBGXtRDZ6gaSgVk4g-xBuUO-wtate5VS_0">

![image](https://github.com/user-attachments/assets/6345cd50-e535-451e-b68f-de98ebdee01c)

**Comment by sunnyyangyangyang** [comment]
L40, 500*700,60frames, 5min(with torch compile) on comfyui

**Comment by jiaxiangc** [comment]
> L40, 500*700,60frames, 5min(with torch compile) on comfyui

如果不使用torch compile，需要多久的时间？
if not use “torch compile”, how much time will take?

**Comment by sunnyyangyangyang** [comment]
> > L40, 500*700,60frames, 5min(with torch compile) on comfyui
> 
> 如果不使用torch compile，需要多久的时间？
> if not use “torch compile”, how much time will take?

从5s/it 到8s/it。 长一些但是能用

**Comment by darknli** [comment]
> > 不太正常，我a100跑是30min左右。不过24g显存竟然能跑的动？我这直接拉到60G。。
> 
> 你这个step设30还是50呢，默认的50我这边A100需要50分钟。

我是30步，50min看起来是正常的

**Comment by wudidiandian** [comment]
如果对视频质量没有强烈的要求，推荐一下kijai的comfyui插件，4060ti,16G vram，低显存那个工作流，5秒视频花费980秒左右。
 另外请教一下各位，开源的这两个版本是只能生成129帧的是视频么？不能生成更长的视频么？我看腾讯官方的示例中有一二十秒的视频？
