### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading file data/3: invalid header or archive is corrupted

### ISSUE THREAD

**Issue by badarrrr** [Tencent/HunyuanVideo#73]
这是报了什么错啊🤯
![image](https://github.com/user-attachments/assets/ade13b95-9bab-4e04-bea3-f0b3ef3b6c21)

![image](https://github.com/user-attachments/assets/63203ff2-3c76-4d70-8df1-87604b15ab57)

**Comment by badarrrr** [comment]
模型是魔搭下载的，会有关系吗？实在不知道哪里有问题 இ௰இ

**Comment by TianQi-777** [comment]
看起来是模型没有下载完整，你根据[ckpts/README](https://github.com/Tencent/HunyuanVideo/blob/main/ckpts/README.md)进行下载。

It seems that the model is not downloaded completely. You can execute the following command according to [ckpts/README](https://github.com/Tencent/HunyuanVideo/blob/main/ckpts/README.md).

**Comment by badarrrr** [comment]
嗯嗯是模型文件问题，谢谢！
