### ISSUE TITLE
Can you share some sample rewritten prompts?

### ISSUE THREAD

**Issue by aikitoria** [Tencent/HunyuanVideo#75]
I see you have a fine tune of Hunyuan-Large to rewrite prompts, but with that being nearly a 400B model, it requires crazy resources to run. Could you share a few samples of what it produces so we can try to approximate those results with smaller models?

**Comment by ckczzj** [comment]
Thanks for your attention! We are currently deploying the prompt rewriting service and it will be updated in the next few days.

**Comment by aikitoria** [comment]
I've rented a 8xH200 SXM server to be able to launch the model, here are the results of throwing in a few prompts of different formats found on the internet:

Input:
`cute girl, red hair`

Output:
`A cute girl with red hair. Realistic, Natural lighting, Casual`

Input:
`girl dancing in her room`
Output:
`A girl dancing in her room. Realistic, Indoor lighting, Casual`

Input:
`anime drawing of a girl dancing in her room`
Output:
`An anime-style drawing of a girl dancing in her room. Natural indoor lighting, Casual`

Input:
`the image is an extreme close up on the face of a 25 year old woman with blonde hair shes tucked in bed with only her nose and eyes visible poking out of the covers and her head on the pillow her nose is pink from the cold and a small trace of her breath condensing in the air can be seen the bed is covered in a knitted patchwork in the background is a tiny bedroom in an olde world cottage with small leaded glass windows the windows are covered in fingers of frost`
Output:
`An extreme close-up shows a 25-year-old blonde woman's face, her nose and eyes peeking out from under the covers. Her pink nose indicates she might have a cold, with a small trail of her breath visible in the air. The bed is covered in a knitted patchwork. In the background, a tiny bedroom in an old-world cottage is seen, with small leaded glass windows covered in frost. Realistic, Natural lighting, Peaceful`

Input:
`score_9, score_8_up, score_7_up, Anime Style, Portrait, yorha no. 2 type b, short white hair, black dress, hairband, clothing cutout, cleavage cutout, puffy sleeves, black hairband, feather-trimmed sleeves, juliet sleeves, mole under mouth, sunset, rubble in the background, depth of field, dynamic angle, fashion photography, sharp`
Output:
`A short-haired woman in a black dress with puffy sleeves and feather-trimmed edges stands out against a sunset backdrop. The woman, identified as Yorha No. 2 Type B, has short white hair, a black hairband, and a mole under her mouth. The scene is set with rubble in the background and uses depth of field and dynamic angles to create a fashion photography style. Realistic, Natural lighting`

Input:
`score_9, score_8_up, score_7_up, score_6_up, source_furry,BREAK,detailed face eyes and fur, 1girl, solo, rabbit girl, clothed, body fur, white rabbit, white fur, detailed fluffy fur, looking at viewer, red eyes, black dress, upper body`
Output:
`A detailed furry scene with a rabbit girl in a black dress. She has fluffy white fur, detailed face with red eyes, and she's looking at the viewer. The shot is a close-up focusing on the upper body. Realistic, Indoor lighting, Intimate`

Input:
`A fluffy dog with a joyful expression, bounding through a snowy landscape under a soft blue sky. Snowflakes are gently falling, and the dog rolls around, pounces into snowdrifts, and digs energetically. Occasionally, the dog pauses, wagging its tail and looking back at the camera, as if inviting you to play. The surroundings feature snow-covered trees, frosted bushes, and a serene winter backdrop. The video is lighthearted, with soft, playful background music to enhance the happy and lively atmosphere.`
Output:
`A fluffy dog with a joyful expression bounds through a snowy landscape under a soft blue sky. Snowflakes gently fall as the dog rolls, pounces into snowdrifts, and digs energetically. Occasionally, the dog pauses, wagging its tail and looking back at the camera, inviting you to play. The surroundings feature snow-covered trees, frosted bushes, and a serene winter backdrop. The video is lighthearted, with soft, playful background music enhancing the happy and lively atmosphere. Realistic, Natural lighting`

**Comment by kathrinawu** [comment]
You can also try with the master mode, the generation video quality will be further improved. We provide two rewrite modes: Normal mode and Master mode. The Master mode enhances the description of aspects such as composition, lighting, and camera movement, which leans towards generating videos with a higher visual quality. but may occasionally result in the loss of some semantic details.

**Comment by aikitoria** [comment]
I am a bit confused by the master mode, actually. The prompts you shared for them are exactly the same, except for the words "normal"/"master". Is that a copy paste error?

The fine tuned model did not seem to react noticeably differently to just that word changing in my tests.

**Comment by shineleex** [comment]
> I am a bit confused by the master mode, actually. The prompts you shared for them are exactly the same, except for the words "normal"/"master". Is that a copy paste error?
> 
> The fine tuned model did not seem to react noticeably differently to just that word changing in my tests.

Thanks for your attention.
That is not a copy-paste error. The fine-tuned model reacts noticeably differently when the original prompt is short. Here are some examples.

Input:
`A large sailing ship sails slowly through the fog.`
Output in normal mode:
`A large sailing ship sails slowly through the fog. Realistic, Natural lighting, Mysterious`
Output in master mode:
`A grand tall ship sails slowly through the mist, its silhouette blending with the fog. The sea surface is calm, with the morning fog slowly dispersing, revealing a mysterious light on the horizon. The overall tone is cool and gray, highlighting the mysterious beauty of the foggy sea. Low angle, the camera follows the scene, full depth of field. Realistic, Natural lighting`

Input:
`A fluffy teddy bear sits on a bed of soft pillows surrounded by children's toys.`
Output in normal mode:
`A fluffy teddy bear sits on a bed of soft pillows, surrounded by children's toys. Realistic, Indoor lighting, Peaceful `
Output in master mode:
`Low angle, the camera movement is Static. Afternoon sunlight filters through half-drawn curtains, casting soft patches of light on fluffy teddy bears sitting on beds of cushions. Scattered around are various children's toys, the overall tone is warm, highlighting the coziness of home and the innocence of childhood. Realistic, Natural lighting, Cozy`
