### ISSUE TITLE
xDiT error CUDA out of memory error on a 4 x RTX6000 Ada on Linux with a total of 192GB VRAM

### ISSUE THREAD

**Issue by AshD** [Tencent/HunyuanVideo#85]
Running on a 4 x RTX6000 Ada on Linux with a total of 192GB VRAM and System memory of 512GB RAM. 
The below command is running out of CUDA memory

torchrun --nproc_per_node=4 sample_video.py \
    --video-size 960 544 \
    --video-length 53 \
    --infer-steps 20 \
    --prompt "A cat walks on the grass, realistic style." \
    --flow-reverse \
    --seed 42 \
    --ulysses-degree 2 \
    --ring-degree 2 \
    --save-path ./results

[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.31 GiB. GPU 0 has a total capacity of 47.40 GiB of which 2.27 GiB is free. Process 10697 has 494.00 MiB memory in use. Process 10698 has 494.00 MiB memory in use. Process 10699 has 494.00 MiB memory in use. Including non-PyTorch memory, this process has 43.64 GiB memory in use. Of the allocated memory 42.52 GiB is allocated by PyTorch, and 81.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by xinpuliu** [comment]
Same situation, the multi GPU mode seems to require more gpu memory than a single card mode, because the same configuration can be run on a single card. I don't know if this is caused by different torch library versions. Looking forward to the author's response.

**Comment by Backroads4Me** [comment]
I'm seeing the same thing.

**Comment by grimulkan** [comment]
The generation does not shard the model across GPUs, but rather copies all weights to each GPU. The weights take about ~24GB without quantizing, so the generation needs to fit in the remaining VRAM.

My guess is they probably never tested at anything less than 80GB VRAM and sized everything for that. The generation _almost_ fits in 48GB, it can probably be optimized. Number of GPUs, ulysses-degree, ring-degree don't seem to affect that VRAM usage.

On the other hand, single GPU generation can use the CPU offload option to fit more than multi GPU can, but obviously is slower. Egs., single Ada6000 can easily generate 65 frames @ 720p.

**Comment by eepson123tw** [comment]
wait for the updates

**Comment by joshilita** [comment]
I'm pretty sure the sample_video.py was supposed to be updated, but it wasn't. 

--ulysses-degree 2 & --ring-degree 2 aren't handled on the script. So I would assume that @JacobKong or someone else forgot to update it for the xdit

**Comment by joshilita** [comment]
> --ulysses-degree 2 & --ring-degree 2 aren't handled on the script. So I would assume that @JacobKong or someone else forgot to update it for the xdit

I actually seem to be completely wrong. The sample_video.py actually forwards the arguments to the pipeline and it seems like the pipelines handles the --ulysses-degree  & --ring-degree. So I don't really know the issue. I too am going through the out of memory error with 4 A100s (160 GB VRAM)

**Comment by joshilita** [comment]
Coming back to this, I didn't have a full understanding on what xdit was actually supposed to do. Now I know. You still need multiple graphics cards that fulfills the minimum VRAM requirement, else you'd still get the cuda out of memory error. As what @grimulkan said. This doesn't split the model across multiple GPUs.

**Comment by AshD** [comment]
xDit looks very interesting
https://github.com/xdit-project/xDiT

PipeFusion support is what I looking for to spread the model across multiple GPUs and it is on the ToDo list for the Hunyuan video.

**Comment by zhangvia** [comment]
> My guess is they probably never tested at anything less than 80GB VRAM and sized everything for that. The generation _almost_ fits in 48GB, it can probably be optimized. Number of GPUs, ulysses-degree, ring-degree don't seem to affect that VRAM usage.

the ulkysses-degree, ring-degree only shard the activations in attention compute process. as for models weights, they just broadcast to every gpu. But considering that most of the GPU memory usage during the inference process of the HunYuan video model is occupied by intermediate activations, partitioning the input variables is expected to theoretically reduce the memory consumption on a single GPU.

**Comment by su400** [comment]
same issue

**Comment by grimulkan** [comment]
> the ulkysses-degree, ring-degree only shard the activations in attention compute process. as for models weights, they just broadcast to every gpu. But considering that most of the GPU memory usage during the inference process of the HunYuan video model is occupied by intermediate activations, partitioning the input variables is expected to theoretically reduce the memory consumption on a single GPU.

I see. You're write in that a lot of the mem usage comes from activations, but the model weights (~24GB) are still pretty large compared to the activations (~36GB). Further, the single-gpu code allows for some components to be offloaded, and therefore ends up using less per-GPU VRAM than even the multi-GPU version.

That said, allowing the weights to be stored as fp8 and quantizing the VAE can help reduce some of that usage, though I think xDIT does not support quantization. Or if not, a combination of the current parallelism with some level of pipeline parallelism can make 720p 129f work across multiple consumer GPUs.

All do-able with the model architecture I think, just needs some focus. For single-GPU, the GGUF and ComfyUI folks as usual have already incorporated it, but it will take some more work to get multi-GPU going, and that is sadly needed for reasonable generation resolution/time/frames.

**Comment by zhangvia** [comment]
> I see. You're right in that a lot of the mem usage comes from activations, but the model weights (~24GB) are still pretty large compared to the activations (~36GB). Further, the single-gpu code allows for some components to be offloaded, and therefore ends up using less per-GPU VRAM than even the multi-GPU version.

if the single gpu version is using cpu offload, less per gpu vram sounds reasonable. but  using deepspeed ulysses and ring attention with a greater number of GPUs will further reduce the memory usage on a single GPU.

 
> That said, allowing the weights to be stored as fp8 and quantizing the VAE can help reduce some of that usage, though I think xDIT does not support quantization. Or if not, a combination of the current parallelism with some level of pipeline parallelism can make 720p 129f work across multiple consumer GPUs.

maybe [optimum-quanto](https://github.com/huggingface/optimum-quanto) can help

**Comment by AshD** [comment]
Once HunyuanVideo has diffusers support, the Hugging Face Accelerate library should be able to handle multi-gpu to spread the model across GPUs.

**Comment by zhangvia** [comment]
> Once HunyuanVideo has diffusers support, the Hugging Face Accelerate library should be able to handle multi-gpu to spread the model across GPUs.

If you are referring to splitting the model across different GPUs and aligning the device of the input parameters with the device of the model weights when executing a block, I have already tried that. However, I encountered an issue: when I split different blocks of the backbone across different GPUs, the attention compute process of the block became significantly slower in computation.
