### ISSUE TITLE
HunyuanVideo model has not undergone NSFW filtering, which is extremely dangerous.

### ISSUE THREAD

**Issue by WangRongsheng** [Tencent/HunyuanVideo#88]
HunyuanVideo poses significant risks, as it generates videos similar to the descriptions provided in any prompts given to it, without exception. I tested it with some NSFW prompts, and it still followed my instructions.

**Comment by WangRongsheng** [comment]
@JacobKong

**Comment by Gobz** [comment]
Oh noooo! The model generated anatomically correct humans, what will become of us?!? 
I think we're ready to ride without the training wheels.

**Comment by seizir** [comment]
The paintbrush poses significant risks, as it deposits paint on the canvas and follows the movements of my hand, without exception. I tried painting some NSFW pictures with it, and it still followed my hand.

**Comment by WangRongsheng** [comment]
> Censorship is dangerous and leads to warping found in SD3. Stop prompting for NSFW things.

I'm really sorry, bro. I just wanted to alert you to the fact that this risk exists. I also love a fully functional HunyuanVideo. Hope you have a great time.
