### ISSUE TITLE
MLLM text encoder

### ISSUE THREAD

**Issue by Bionagato** [Tencent/HunyuanVideo#93]
Hi, this model is really incredible, but it is really hard to control the outputs. When will you release the MLLM Text Encoder? It seems necessary to control the model's outputs. With Llama, it is really hard, if not impossible, to get videos as good as those published on the project page. It would also be good to have some examples of how the videos in the dataset were captioned to get an idea of how to format the prompts.

**Comment by breadbrowser** [comment]
[the text Text Encoder is t5 flan xxl ](https://huggingface.co/tencent/HunyuanVideo#mllm-text-encoder)

**Comment by win10ogod** [comment]
> [the text Text Encoder is t5 flan xxl ](https://huggingface.co/tencent/HunyuanVideo#mllm-text-encoder)

MLLM is based on causal attention while T5-XXL utilizes bidirectional attention
From this we can see that it should not be t5!

**Comment by kathrinawu** [comment]
Please refer to this https://github.com/Tencent/HunyuanVideo/blob/main/ckpts/README.md
