### ISSUE TITLE
Running Hunyuan Video on 4 x 3090 Graphics Cards

### ISSUE THREAD

**Issue by Smiden3** [Tencent/HunyuanVideo#96]
Hello! I was lucky enough to have access to a Windows-based system with a 4 graphics card and a 3090. I installed and started the video generator using ComfyUI. But right now I'm only using 24GB of GPUs out of 96. Could you talk about using XDIT for parallel use? I will be glad to have any information on this topic, thank you
![Screenshot_20241209_183209_Browser](https://github.com/user-attachments/assets/7922dd35-0572-49db-a6d4-424aadb1218e)
![Screenshot_20241209_183233_Browser](https://github.com/user-attachments/assets/78bd74d8-4685-4e3c-92eb-835011a71c3c)

**Comment by Lissanro** [comment]
My configuration is similar, except I am on Linux. I have four 3090, so 96GB of VRAM in total, but how to utilize all the cards? If this is not supported yet, please consider this as a feature request, because currently using multiple 24GB cards is the only way to get high VRAM at a reasonable price.

**Comment by feifeibear** [comment]
At present, the xDiT has not yet been tested within ComfyUI, and it appears that four 3090 GPUs may not suffice to meet the memory demands of HunayunVideo. However, we are considering exploring ComfyUI in the near future.

**Comment by Smiden3** [comment]
In principle, I don't mind if with XDiT I can use a 4 graphics card via the command line. But I've never worked with the command line in this format, so I'd like to know if there is a detailed and step-by-step guide (text, video) on how to run video generation?

**Comment by feifeibear** [comment]
You can follow the instructions in the README and run it from the command line. However, I need to remind you that running HunyuanVideo on four 3090 GPUs is not feasible due to the substantial memory requirements of the model.

https://github.com/xdit-project/HunyuanVideo-xDiT?tab=readme-ov-file#parallel-inference-on-multiple-gpus-by-xdit

**Comment by Smiden3** [comment]
I've seen the quick startup, this should really help me figure out how to start properly, however, the examples don't include running Hunyuan Video. 
![Screenshot_20241210_095310_Browser](https://github.com/user-attachments/assets/e7550ba2-bb18-491a-b012-d15d1c4e26f7)
![Screenshot_20241210_095143_Browser](https://github.com/user-attachments/assets/b7678c4f-c021-4719-bca9-adfb39d90f08)

**Comment by feifeibear** [comment]
https://github.com/xdit-project/HunyuanVideo-xDiT?tab=readme-ov-file#parallel-inference-on-multiple-gpus-by-xdit

Please follow the instructions in HunyuanVideo readme!

**Comment by Smiden3** [comment]
> You can follow the instructions in the README and run it from the command line. However, I need to remind you that running HunyuanVideo on four 3090 GPUs is not feasible due to the substantial memory requirements of the model.
> 
> https://github.com/xdit-project/HunyuanVideo-xDiT?tab=readme-ov-file#parallel-inference-on-multiple-gpus-by-xdit

I also wonder why you say that there is not enough computing power. I can run the model even on a single 3090 graphics card, but of course I can't use a resolution of 1280/720 at 50 steps, but I can use a lower resolution.

**Comment by Smiden3** [comment]
> [https://github.com/xdit-project/HunyuanVideo-xDiT?tab=readme-ov-file#параллельное выполнение на нескольких графических процессорах с помощью xdit](https://github.com/xdit-project/HunyuanVideo-xDiT?tab=readme-ov-file#parallel-inference-on-multiple-gpus-by-xdit)
> 
> Пожалуйста, следуйте инструкциям в HunyuanVideo readme!

![Screenshot_20241210_100351_Samsung Internet](https://github.com/user-attachments/assets/87c5e76a-c84b-4338-b38e-7bc7a0886662)
This is what I see when I click on the link

**Comment by feifeibear** [comment]
@Smiden3 sorry! its all my fault. The link should be:

https://github.com/Tencent/HunyuanVideo?tab=readme-ov-file#-parallel-inference-on-multiple-gpus-by-xdit

Sorry, I pointed you to a private repo.

**Comment by Smiden3** [comment]
thank you @feifeibear

**Comment by doogyhatts** [comment]
> At present, the xDiT has not yet been tested within ComfyUI, and it appears that four 3090 GPUs may not suffice to meet the memory demands of HunayunVideo. However, we are considering exploring ComfyUI in the near future.

Just curious on the memory allocation for the model under xDiT conditions. 
Does each GPU loads a copy of the model or the model is still loaded once?
I can understand why using 4x3090 will not work if the 25gb model has to be loaded on each GPU.

**Comment by feifeibear** [comment]
> > At present, the xDiT has not yet been tested within ComfyUI, and it appears that four 3090 GPUs may not suffice to meet the memory demands of HunayunVideo. However, we are considering exploring ComfyUI in the near future.
> 
> Just curious on the memory allocation for the model under xDiT conditions. Does each GPU loads a copy of the model or the model is still loaded once? I can understand why using 4x3090 will not work if the 25gb model has to be loaded on each GPU.

The model is replicated on each GPUs when using sequence parallel. But we have other parallel approaches with lower memory requirements. If you are interested, you can find them in our xDiT paper.

https://arxiv.org/abs/2411.01738

**Comment by doogyhatts** [comment]
> The model is replicated on each GPUs when using sequence parallel. But we have other parallel approaches with lower memory requirements. If you are interested, you can find them in our xDiT paper.
> 
> https://arxiv.org/abs/2411.01738
Thanks for the clarification!

**Comment by rzgarespo** [comment]
> My configuration is similar, except I am on Linux. I have four 3090, so 96GB of VRAM in total, but how to utilize all the cards?
> 
> EDIT: I know there are some command-line examples for xDiT, but just like the person who reported this bug, it is unclear to me how to get this working in ComfyUI, or it is not supported yet?

I've RTX3080 and 96GB DDR4 RAM
https://www.youtube.com/watch?v=ylfeJ7Cv8AE

**Comment by lamarquenet** [comment]
We really need a solution for running this on 4 3090 cards
